config/routes.rb
Rails.application.routes.draw do
  # resources :pages
  get 'pages/index'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/faq'
  get 'pages/login'
  resources :articles
  # root 'articles#index'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many_attached :images

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :author, :body, :published_on, :image_url, images: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="form-data">
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title ,class:"field-area" %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author ,class:"field-area" %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body ,class:"field-area" %>
  </div>

  <div class="field">
    <%= form.label :published_on %>
    <%= form.date_select :published_on ,class:"field-area" %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url ,class:"field-area" %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true ,class:"field-area" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<div class="container">
  <% @articles.each do |article| %>
    <main class="grid">
      <article>
        <%= image_tag("book.jpg", class:"img-fluid") %>
        <div class="text">
          <h3><%= article.title %></h3>
          <h4><%= article.author %></h4>
          <h5><%= article.published_on %></h5>
          <p class="textControl"><%= article.body %></p>        
          <div class="textControl" style='display:none;'><%= truncate = '(article.body, length:15)' %></div>
          <div class="textControl" style='display:none;'><%= article.body %></div>
        </div><!-- text ends -->
        <%= link_to 'Show', article %>
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
      </article> 
    </main>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    // Configure/customize these variables.
    var showChar = 15;  // How many characters are shown by default
    var ellipsestext = "...";
    var moretext = "Read more";
    var lesstext = "Read less";
    

    $('.textControl').each(function() {
        var content = $(this).html();
 
        if(content.length > showChar) {
 
            var c = content.substr(0, showChar);
            var h = content.substr(showChar, content.length - showChar);
 
            var html = c + '<span class="moreellipses">' + ellipsestext+ '&nbsp;</span><span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">' + moretext + '</a></span>';
 
            $(this).html(html);
        }
    });
 
    $(".morelink").click(function(){
        if($(this).hasClass("less")) {
            $(this).removeClass("less");
            $(this).html(moretext);
        } else {
            $(this).addClass("less");
            $(this).html(lesstext);
        }
        $(this).parent().prev().toggle();
        $(this).prev().toggle();
        return false;
    });
});
</script>




<%= link_to 'New Article', new_article_path , id:"newart" %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="showform">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @article.published_on %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @article.image_url %>
</p>

<p>
  <% (0...@article.images.count).each do |image| %>
    <div class="form-image">
      <%= image_tag @article.images[image],class:'actual-image' %>
    </div>
  <%end%>
</p>
</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Maroon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

  </head>

  <body>
  
   
 <header>
    <h1 class="logo">Maroon</h1>
    <input type="checkbox" id="nav-toggle" class="nav-toggle">
      <nav>
        <ul>
          <li><a><%= link_to "Home",root_path %></a></li>
          <li><a><%= link_to "About",pages_about_path %></a></li>
          <li><a><%= link_to "Contact",pages_contact_path %></a></li>
          <li><a><%= link_to "FAQ", pages_faq_path %></a></li>
          <li><a><%= link_to "Login",pages_login_path %></a></li>
        </ul>
      </nav>

    <label for="nav-toggle" class="nav-toggle-label">
      <span></span>
    </label>
  </header>
   

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="about">
  <div class="row">
    <h1>About Maroon</h1>
      <p>Maroon started as a journey into knowing Ruby and Ruby on Rails.</p>
      <p>Simple syntax is the key takeaway from this language.</p>
      <br>
      <p>In layman's terms, this is like cake. And it subtly stands out from the rest.More of like the shiny new toy at the toy store. </p>
      <p>So if you have had a quirky , funny or disastrous story. This is the place for   you to be. We would not judge you but profanity is a strict NO-NO. </p>

      <blockquote id="about-quote">
        <i><b>If you know what you want with my syntax, I shall deliver accordingly.
                                                                   -- Ruby</b></i>
      </blockquote>
  </div>

 
</div>

app/views/pages/contact.html.erb
<div class="contact">
  <h1 class="contact-header">Conatct Us</h1>
    <div class="cotact-content">
      <p>You can call us at +91 xxx-xxx-xxxx or email us at mymail@gmail.com</p>
      
      <p>Or do drop by. We are nearer than you expect us to be. Just follow along the map below.</p>
      <iframe width="600" height="450" style="border:0" loading="lazy" allowfullscreen src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ7YSPdC0TtzsRpCbfPzfT9ls&key=AIzaSyBTweK2YReaxHwVetkpL7F1LrdkDNLPej8"></iframe>
    </div>
</div>

app/views/pages/faq.html.erb
<div class="faqtop">

<div class="faqhead">
<h1>FAQ</h1>
</div>  

<h2 class="que1"> Question 1</h2>
<p>It can be any dummy text. blah blah blah.</p>

<h2 class="que1"> Question 2</h2>
<p>It can be any dummy text. blah blah blah.</p>

<h2 class="que1"> Question 3</h2>
<p>It can be any dummy text. blah blah blah.</p>

<h2 class="que1"> Question 4</h2>
<p>It can be any dummy text. blah blah blah.</p>

</div>

app/views/pages/index.html.erb
<div class="homepg-top">
  <h1>Maroon</h1>
  <p id="homepg">Welcome to Maroon.A place for all your Ruby and Rails related stories.</p>
</div>

<div class="wrap">
  <div class="wrap-content">
    <div class="pics">
      <%= image_tag ("maroon1.jpg"), class:"pic-det" %>
    </div>

    <div class="pics">
      <%= image_tag ("maroon2.jpg"), class:"pic-det" %>
    </div>

    <div class="pics">
      <%= image_tag ("maroon3.jpg"), class:"pic-det" %>
    </div>

    <div class="pics">
      <%= image_tag ("maroon4.jpg"), class:"pic-det" %>
    </div>

    <div class="pics">
      <%= image_tag ("maroon.jpg"), class:"pic-det" %>
    </div>

    <div class="pics">
      <%= image_tag ("maroon6.jpg"), class:"pic-det" %>
    </div>
    
    <div class="pics">
      <%= image_tag ("maroon7.jpg"), class:"pic-det" %>
    </div>

    <div class="pics">
      <%= image_tag ("maroon8.jpg"), class:"pic-det" %>
    </div>

    <div class="pics">
      <%= image_tag ("maroon9.jpg"), class:"pic-det" %>
    </div>

    <div class="pics">
      <%= image_tag ("maroon10.jpg"), class:"pic-det" %>
    </div>
  </div>
</div>

app/views/pages/login.html.erb
<h1>Pages#login</h1>
<p>Find me in app/views/pages/login.html.erb</p>